"""
HackerRank - Project Euler 002

https://www.hackerrank.com/contests/projecteuler/challenges/euler002/problem
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed N,
find the sum of the even-valued terms.

"""


def fibonacci_even_sum(limit):
    """ returns the sum of the even-valued terms """
    if limit < 2:
        return 0
    if limit < 3:
        return 2

    n_0 = 1
    n_1 = 2
    even_sum = 2
    current = n_1 + n_0

    while current <= limit:
        if current % 2 == 0:
            even_sum += current
        n_0 = n_1
        n_1 = current
        current = n_1 + n_0
    return even_sum


def main():
    """ main """
    limit = 100
    print(fibonacci_even_sum(limit))


if __name__ == '__main__':
    main()
