A = set([1, 2, 3])
B = set([3, 4, 5])
print(A.difference(B))
print(A.symmetric_difference(B))
print(A.union(B))
print(A.intersection(B))
print()
print(B.difference(A))
print(B.symmetric_difference(A))
print(B.union(A))
print(B.intersection(A))
